### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by spindev**

### CODE REVIEW

**Review by wn00901205 — COMMENTED** [review]
passt

**Review by spindev — COMMENTED** [review]
@wn00901205 What do you think?

**Review by ANDRAM42 — COMMENTED** [review]
➡️ ⏭️ 👍

**Review by ANDRAM42 — APPROVED** [review]
👍

**Review by ANDRAM42 — CHANGES_REQUESTED** [review]
👎

**Review by wn00901205 — APPROVED** [review]
ok, approved

**Pull request merged**
